<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <NeutralLanguage>en-US</NeutralLanguage>
        <AssemblyName>Overlayer.Module.ADOFAI</AssemblyName>
        <LangVersion>latest</LangVersion>
        <OverlayerPath Condition="'$(OverlayerPath)' == ''">../../Overlayer/Overlayer</OverlayerPath>
    </PropertyGroup>

    <PropertyGroup>
        <!-- O5Kit (UI + input toolkit). Module is Mono-only: Debug/Release map to O5Kit *_Mono. -->
        <O5KitProject>$(MSBuildProjectDirectory)/../../O5Kit/src/O5Kit/O5Kit.csproj</O5KitProject>
        <O5KitConfiguration Condition="$(Configuration.Contains('Debug'))">Debug_Mono</O5KitConfiguration>
        <O5KitConfiguration Condition="!$(Configuration.Contains('Debug'))">Release_Mono</O5KitConfiguration>
        <UnityPath Condition="'$(UnityPath)' == '' and Exists('/home/kkitut/.local/share/Steam/steamapps/common/Melatonin/Melatonin_Data/Managed/UnityEngine.CoreModule.dll')">/home/kkitut/.local/share/Steam/steamapps/common/Melatonin/Melatonin_Data/Managed</UnityPath>
        <UnityPath Condition="'$(UnityPath)' == ''">$(GamePath)/$(GameData)/Managed</UnityPath>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(O5KitProject)">
            <SetConfiguration>Configuration=$(O5KitConfiguration)</SetConfiguration>
            <SetTargetFramework>TargetFramework=netstandard2.0</SetTargetFramework>
        </ProjectReference>
    </ItemGroup>
	
    <ItemGroup>
		<Reference Include="Overlayer" HintPath="$(OverlayerPath)/bin/Release_ML/netstandard2.0/Overlayer.dll" />
        <Reference Include="0Harmony" HintPath="$(GamePath)/MelonLoader/net35/0Harmony.dll" />
        <Reference Include="Accessibility" HintPath="$(GamePath)/$(GameData)/Managed/Accessibility.dll" />
        <Reference Include="DemiLib" HintPath="$(GamePath)/$(GameData)/Managed/DemiLib.dll" />
        <Reference Include="DOTween" HintPath="$(GamePath)/$(GameData)/Managed/DOTween.dll" />
        <Reference Include="DOTweenPro" HintPath="$(GamePath)/$(GameData)/Managed/DOTweenPro.dll" />
        <Reference Include="I18N.CJK" HintPath="$(GamePath)/$(GameData)/Managed/I18N.CJK.dll" />
        <Reference Include="I18N" HintPath="$(GamePath)/$(GameData)/Managed/I18N.dll" />
        <Reference Include="I18N.MidEast" HintPath="$(GamePath)/$(GameData)/Managed/I18N.MidEast.dll" />
        <Reference Include="I18N.Other" HintPath="$(GamePath)/$(GameData)/Managed/I18N.Other.dll" />
        <Reference Include="I18N.Rare" HintPath="$(GamePath)/$(GameData)/Managed/I18N.Rare.dll" />
        <Reference Include="I18N.West" HintPath="$(GamePath)/$(GameData)/Managed/I18N.West.dll" />
        <Reference Include="Mono.Data.Sqlite" HintPath="$(GamePath)/$(GameData)/Managed/Mono.Data.Sqlite.dll" />
        <Reference Include="Mono.Posix" HintPath="$(GamePath)/$(GameData)/Managed/Mono.Posix.dll" />
        <Reference Include="Mono.WebBrowser" HintPath="$(GamePath)/$(GameData)/Managed/Mono.WebBrowser.dll" />
        <Reference Include="Newtonsoft.Json" HintPath="$(GamePath)/$(GameData)/Managed/Newtonsoft.Json.dll" />
        <Reference Include="Novell.Directory.Ldap" HintPath="$(GamePath)/$(GameData)/Managed/Novell.Directory.Ldap.dll" />
        <Reference Include="Ookii.Dialogs" HintPath="$(GamePath)/$(GameData)/Managed/Ookii.Dialogs.dll" />
        <Reference Include="Purchasing.Common" HintPath="$(GamePath)/$(GameData)/Managed/Purchasing.Common.dll" />
        <Reference Include="RDTools" HintPath="$(GamePath)/$(GameData)/Managed/RDTools.dll" />
        <Reference Include="Rewired_Core" HintPath="$(GamePath)/$(GameData)/Managed/Rewired_Core.dll" />
        <Reference Include="SkyHook.Unity" HintPath="$(GamePath)/$(GameData)/Managed/SkyHook.Unity.dll" />
        <Reference Include="Rewired_Windows" HintPath="$(GamePath)/$(GameData)/Managed/Rewired_Windows.dll" />
        <Reference Include="Rewired_Windows_Functions" HintPath="$(GamePath)/$(GameData)/Managed/Rewired_Windows_Functions.dll" />
        <Reference Include="Unity.Addressables" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Addressables.dll" />
        <Reference Include="Unity.Burst" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Burst.dll" />
        <Reference Include="Unity.Burst.Unsafe" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Burst.Unsafe.dll" />
        <Reference Include="Unity.Collections" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Collections.dll" />
        <Reference Include="Unity.Collections.LowLevel.ILSupport" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Collections.LowLevel.ILSupport.dll" />
        <Reference Include="Unity.Mathematics" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Mathematics.dll" />
        <Reference Include="Unity.MemoryProfiler" HintPath="$(GamePath)/$(GameData)/Managed/Unity.MemoryProfiler.dll" />
        <Reference Include="Unity.Profiling.Core" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Profiling.Core.dll" />
        <Reference Include="Unity.ResourceManager" HintPath="$(GamePath)/$(GameData)/Managed/Unity.ResourceManager.dll" />
        <Reference Include="Unity.ScriptableBuildPipeline" HintPath="$(GamePath)/$(GameData)/Managed/Unity.ScriptableBuildPipeline.dll" />
        <Reference Include="Unity.Services.Core" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.dll" />
        <Reference Include="Unity.Services.Core.Analytics" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Analytics.dll" />
        <Reference Include="Unity.Services.Core.Components" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Components.dll" />
        <Reference Include="Unity.Services.Core.Configuration" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Configuration.dll" />
        <Reference Include="Unity.Services.Core.Device" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Device.dll" />
        <Reference Include="Unity.Services.Core.Environments" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Environments.dll" />
        <Reference Include="Unity.Services.Core.Environments.Internal" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Environments.Internal.dll" />
        <Reference Include="Unity.Services.Core.Internal" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Internal.dll" />
        <Reference Include="Unity.Services.Core.Networking" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Networking.dll" />
        <Reference Include="Unity.Services.Core.Registration" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Registration.dll" />
        <Reference Include="Unity.Services.Core.Scheduler" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Scheduler.dll" />
        <Reference Include="Unity.Services.Core.Telemetry" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Telemetry.dll" />
        <Reference Include="Unity.Services.Core.Threading" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Threading.dll" />
        <Reference Include="Unity.TextMeshPro" HintPath="$(UnityPath)/Unity.TextMeshPro.dll" />
        <Reference Include="UnityEngine" HintPath="$(UnityPath)/UnityEngine.dll" />
        <Reference Include="UnityEngine.AccessibilityModule" HintPath="$(UnityPath)/UnityEngine.AccessibilityModule.dll" />
        <Reference Include="UnityEngine.AIModule" HintPath="$(UnityPath)/UnityEngine.AIModule.dll" />
        <Reference Include="UnityEngine.AndroidJNIModule" HintPath="$(UnityPath)/UnityEngine.AndroidJNIModule.dll" />
        <Reference Include="UnityEngine.AnimationModule" HintPath="$(UnityPath)/UnityEngine.AnimationModule.dll" />
        <Reference Include="UnityEngine.ARModule" HintPath="$(UnityPath)/UnityEngine.ARModule.dll" />
        <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(UnityPath)/UnityEngine.AssetBundleModule.dll" />
        <Reference Include="UnityEngine.AudioModule" HintPath="$(UnityPath)/UnityEngine.AudioModule.dll" />
        <Reference Include="UnityEngine.ClothModule" HintPath="$(UnityPath)/UnityEngine.ClothModule.dll" />
        <Reference Include="UnityEngine.ClusterInputModule" HintPath="$(UnityPath)/UnityEngine.ClusterInputModule.dll" />
        <Reference Include="UnityEngine.ClusterRendererModule" HintPath="$(UnityPath)/UnityEngine.ClusterRendererModule.dll" />
        <Reference Include="UnityEngine.ContentLoadModule" HintPath="$(UnityPath)/UnityEngine.ContentLoadModule.dll" />
        <Reference Include="UnityEngine.CoreModule" HintPath="$(UnityPath)/UnityEngine.CoreModule.dll" />
        <Reference Include="UnityEngine.CrashReportingModule" HintPath="$(UnityPath)/UnityEngine.CrashReportingModule.dll" />
        <Reference Include="UnityEngine.DirectorModule" HintPath="$(UnityPath)/UnityEngine.DirectorModule.dll" />
        <Reference Include="UnityEngine.DSPGraphModule" HintPath="$(UnityPath)/UnityEngine.DSPGraphModule.dll" />
        <Reference Include="UnityEngine.GameCenterModule" HintPath="$(UnityPath)/UnityEngine.GameCenterModule.dll" />
        <Reference Include="UnityEngine.GIModule" HintPath="$(UnityPath)/UnityEngine.GIModule.dll" />
        <Reference Include="UnityEngine.GridModule" HintPath="$(UnityPath)/UnityEngine.GridModule.dll" />
        <Reference Include="UnityEngine.HotReloadModule" HintPath="$(UnityPath)/UnityEngine.HotReloadModule.dll" />
        <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(UnityPath)/UnityEngine.ImageConversionModule.dll" />
        <Reference Include="UnityEngine.IMGUIModule" HintPath="$(UnityPath)/UnityEngine.IMGUIModule.dll" />
        <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(UnityPath)/UnityEngine.InputLegacyModule.dll" />
        <Reference Include="UnityEngine.InputModule" HintPath="$(UnityPath)/UnityEngine.InputModule.dll" />
        <Reference Include="UnityEngine.JSONSerializeModule" HintPath="$(UnityPath)/UnityEngine.JSONSerializeModule.dll" />
        <Reference Include="UnityEngine.LocalizationModule" HintPath="$(UnityPath)/UnityEngine.LocalizationModule.dll" />
        <Reference Include="UnityEngine.NVIDIAModule" HintPath="$(UnityPath)/UnityEngine.NVIDIAModule.dll" />
        <Reference Include="UnityEngine.ParticleSystemModule" HintPath="$(UnityPath)/UnityEngine.ParticleSystemModule.dll" />
        <Reference Include="UnityEngine.PerformanceReportingModule" HintPath="$(UnityPath)/UnityEngine.PerformanceReportingModule.dll" />
        <Reference Include="UnityEngine.Physics2DModule" HintPath="$(UnityPath)/UnityEngine.Physics2DModule.dll" />
        <Reference Include="UnityEngine.PhysicsModule" HintPath="$(UnityPath)/UnityEngine.PhysicsModule.dll" />
        <Reference Include="UnityEngine.ProfilerModule" HintPath="$(UnityPath)/UnityEngine.ProfilerModule.dll" />
        <Reference Include="UnityEngine.PropertiesModule" HintPath="$(UnityPath)/UnityEngine.PropertiesModule.dll" />
        <Reference Include="UnityEngine.Purchasing" HintPath="$(UnityPath)/UnityEngine.Purchasing.dll" />
        <Reference Include="UnityEngine.Purchasing.AppleCore" HintPath="$(UnityPath)/UnityEngine.Purchasing.AppleCore.dll" />
        <Reference Include="UnityEngine.Purchasing.AppleMacosStub" HintPath="$(UnityPath)/UnityEngine.Purchasing.AppleMacosStub.dll" />
        <Reference Include="UnityEngine.Purchasing.AppleStub" HintPath="$(UnityPath)/UnityEngine.Purchasing.AppleStub.dll" />
        <Reference Include="UnityEngine.Purchasing.Codeless" HintPath="$(UnityPath)/UnityEngine.Purchasing.Codeless.dll" />
        <Reference Include="UnityEngine.Purchasing.SecurityCore" HintPath="$(UnityPath)/UnityEngine.Purchasing.SecurityCore.dll" />
        <Reference Include="UnityEngine.Purchasing.SecurityStub" HintPath="$(UnityPath)/UnityEngine.Purchasing.SecurityStub.dll" />
        <Reference Include="UnityEngine.Purchasing.Stores" HintPath="$(UnityPath)/UnityEngine.Purchasing.Stores.dll" />
        <Reference Include="UnityEngine.Purchasing.WinRTCore" HintPath="$(UnityPath)/UnityEngine.Purchasing.WinRTCore.dll" />
        <Reference Include="UnityEngine.Purchasing.WinRTStub" HintPath="$(UnityPath)/UnityEngine.Purchasing.WinRTStub.dll" />
        <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule" HintPath="$(UnityPath)/UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll" />
        <Reference Include="UnityEngine.ScreenCaptureModule" HintPath="$(UnityPath)/UnityEngine.ScreenCaptureModule.dll" />
        <Reference Include="UnityEngine.SharedInternalsModule" HintPath="$(UnityPath)/UnityEngine.SharedInternalsModule.dll" />
        <Reference Include="UnityEngine.SpriteMaskModule" HintPath="$(UnityPath)/UnityEngine.SpriteMaskModule.dll" />
        <Reference Include="UnityEngine.SpriteShapeModule" HintPath="$(UnityPath)/UnityEngine.SpriteShapeModule.dll" />
        <Reference Include="UnityEngine.StreamingModule" HintPath="$(UnityPath)/UnityEngine.StreamingModule.dll" />
        <Reference Include="UnityEngine.SubstanceModule" HintPath="$(UnityPath)/UnityEngine.SubstanceModule.dll" />
        <Reference Include="UnityEngine.SubsystemsModule" HintPath="$(UnityPath)/UnityEngine.SubsystemsModule.dll" />
        <Reference Include="UnityEngine.TerrainModule" HintPath="$(UnityPath)/UnityEngine.TerrainModule.dll" />
        <Reference Include="UnityEngine.TerrainPhysicsModule" HintPath="$(UnityPath)/UnityEngine.TerrainPhysicsModule.dll" />
        <Reference Include="UnityEngine.TextCoreModule" Condition="Exists('$(UnityPath)/UnityEngine.TextCoreModule.dll')" HintPath="$(UnityPath)/UnityEngine.TextCoreModule.dll" />
        <Reference Include="UnityEngine.TextCoreFontEngineModule" Condition="Exists('$(UnityPath)/UnityEngine.TextCoreFontEngineModule.dll')" HintPath="$(UnityPath)/UnityEngine.TextCoreFontEngineModule.dll" />
        <Reference Include="UnityEngine.TextCoreTextEngineModule" Condition="Exists('$(UnityPath)/UnityEngine.TextCoreTextEngineModule.dll')" HintPath="$(UnityPath)/UnityEngine.TextCoreTextEngineModule.dll" />
        <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(UnityPath)/UnityEngine.TextRenderingModule.dll" />
        <Reference Include="UnityEngine.TilemapModule" HintPath="$(UnityPath)/UnityEngine.TilemapModule.dll" />
        <Reference Include="UnityEngine.TLSModule" HintPath="$(UnityPath)/UnityEngine.TLSModule.dll" />
        <Reference Include="UnityEngine.UI" HintPath="$(UnityPath)/UnityEngine.UI.dll" />
        <Reference Include="UnityEngine.UIElementsModule" HintPath="$(UnityPath)/UnityEngine.UIElementsModule.dll" />
        <Reference Include="UnityEngine.UIModule" HintPath="$(UnityPath)/UnityEngine.UIModule.dll" />
        <Reference Include="UnityEngine.UmbraModule" HintPath="$(UnityPath)/UnityEngine.UmbraModule.dll" />
        <Reference Include="UnityEngine.UnityAnalyticsCommonModule" HintPath="$(UnityPath)/UnityEngine.UnityAnalyticsCommonModule.dll" />
        <Reference Include="UnityEngine.UnityAnalyticsModule" HintPath="$(UnityPath)/UnityEngine.UnityAnalyticsModule.dll" />
        <Reference Include="UnityEngine.UnityConnectModule" HintPath="$(UnityPath)/UnityEngine.UnityConnectModule.dll" />
        <Reference Include="UnityEngine.UnityCurlModule" HintPath="$(UnityPath)/UnityEngine.UnityCurlModule.dll" />
        <Reference Include="UnityEngine.UnityTestProtocolModule" HintPath="$(UnityPath)/UnityEngine.UnityTestProtocolModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule" HintPath="$(UnityPath)/UnityEngine.UnityWebRequestAssetBundleModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestAudioModule" HintPath="$(UnityPath)/UnityEngine.UnityWebRequestAudioModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="$(UnityPath)/UnityEngine.UnityWebRequestModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestTextureModule" HintPath="$(UnityPath)/UnityEngine.UnityWebRequestTextureModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestWWWModule" HintPath="$(UnityPath)/UnityEngine.UnityWebRequestWWWModule.dll" />
        <Reference Include="UnityEngine.VehiclesModule" HintPath="$(UnityPath)/UnityEngine.VehiclesModule.dll" />
        <Reference Include="UnityEngine.VFXModule" HintPath="$(UnityPath)/UnityEngine.VFXModule.dll" />
        <Reference Include="UnityEngine.VideoModule" HintPath="$(UnityPath)/UnityEngine.VideoModule.dll" />
        <Reference Include="UnityEngine.VirtualTexturingModule" HintPath="$(UnityPath)/UnityEngine.VirtualTexturingModule.dll" />
        <Reference Include="UnityEngine.VRModule" HintPath="$(UnityPath)/UnityEngine.VRModule.dll" />
        <Reference Include="UnityEngine.WindModule" HintPath="$(UnityPath)/UnityEngine.WindModule.dll" />
        <Reference Include="UnityEngine.XRModule" HintPath="$(UnityPath)/UnityEngine.XRModule.dll" />
    </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resource\Embedded\**\*" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="Build" Condition="'$(SkipPostBuild)' != 'true'">
        <MakeDir Directories="$(GamePath)/UserLibs" Condition="'$(TargetPath)' != ''" />
        <Copy Condition="'$(TargetPath)' != ''" SourceFiles="$(TargetPath)" DestinationFolder="$(GamePath)/UserLibs" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)O5Kit.dll" DestinationFolder="$(GamePath)/UserLibs" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)O5Kit.dll')" />

		<ItemGroup>
			<ExportFiles Include="Resource/Export/**/*.*" />
		</ItemGroup>

		<MakeDir Directories="$(GamePath)/UserData/Overlayer/Module/ADOFAI/" />
		<Copy SourceFiles="@(ExportFiles)" DestinationFiles="@(ExportFiles->'$(GamePath)/UserData/Overlayer/Module/ADOFAI/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />

        <PropertyGroup>
            <SolutionRoot Condition="'$(SolutionDir)' != '' And '$(SolutionDir)' != '*Undefined*'">$(SolutionDir)</SolutionRoot>
            <SolutionRoot Condition="'$(SolutionDir)' == '' Or '$(SolutionDir)' == '*Undefined*'">$(MSBuildProjectDirectory)\..\</SolutionRoot>
            <BuildOutputDir>$(SolutionRoot)\.build\$(Configuration)\$(TargetName)</BuildOutputDir>
        </PropertyGroup>
        <MakeDir Directories="$(BuildOutputDir)\UserLibs" Condition="'$(TargetPath)' != ''" />
        <Copy Condition="'$(TargetPath)' != ''" SourceFiles="$(TargetPath)" DestinationFolder="$(BuildOutputDir)\UserLibs" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)O5Kit.dll" DestinationFolder="$(BuildOutputDir)\UserLibs" SkipUnchangedFiles="true" Condition="Exists('$(TargetDir)O5Kit.dll')" />
        <MakeDir Directories="$(BuildOutputDir)\UserData\Overlayer\Module\ADOFAI" />
        <Copy SourceFiles="@(ExportFiles)" DestinationFiles="@(ExportFiles->'$(BuildOutputDir)\UserData\Overlayer\Module\ADOFAI\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    </Target>
</Project>
